# Generated by Django 3.1.7 on 2021-05-04 12:09

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('author_id', models.IntegerField()),
                ('likes', models.IntegerField(default=0)),
                ('popularity', models.FloatField()),
                ('reads', models.BigIntegerField()),
                ('tags', jsonfield.fields.JSONField()),
            ],
        ),
    ]
